export enum ErrorCode {
  WALLET_NOT_FOUND = "E001",
  CURRENCY_NOT_FOUND = "E002",
  CURRENCY_ALREADY_EXISTS = "E003",
  CURRENCY_MALFORMED = "E004",
  CURRENCY_NOT_SUPPORTED = "E005",
  PAYLOAD_MALFORMED = "E006",
  WALLET_MALFORMED = "E007",
}
