openapi: '3.0.0'
info:
  title: Wallet
  version: '1.0.0'
  description: Wallet manager


paths:
  /wallet:
    get:
      summary: "List all Wallets"
      parameters:
        - name: wallet_id
          schema:
            type: string
      responses:
        200:
          description: "Ok operation to list all wallets"
          content:
            application/json :
              schema:
                type: array
                itmes:
                  $ref: '#/components/schemas/wallet'
        404:
          description: "The wallet was not found"
          content:
            application/json :
              schema:
                type: array
                itmes:
                  $ref: '#/components/schemas/error'

    post:
      summary: "List all Wallets"
      parameters:
        - name: wallet_id
          schema:
            type: string
      responses:
        200:
          description: "Ok operation to list all wallets"
          content:
            application/json :
              schema:
                type: array
                itmes:
                  $ref: '#/components/schemas/wallet'
        404:
          description: "The wallet was not found"
          content:
            application/json :
              schema:
                type: array
                itmes:
                  $ref: '#/components/schemas/error'
    delete:
      summary: "List all Wallets"
      parameters:
        - name: wallet_id
          schema:
            type: string
      responses:
        200:
          description: "Ok operation to list all wallets"
          content:
            application/json :
              schema:
                type: array
                itmes:
                  $ref: '#/components/schemas/wallet'
        404:
          description: "The wallet was not found"
          content:
            application/json :
              schema:
                type: array
                itmes:
                  $ref: '#/components/schemas/error'


components:
  schemas:
    currency:
      type: object
      properties:
        value:
          type: integer
          minimum: 0
          description: Currency value
        name:
          type: string
          description: Currency Name

    wallet:
      type: object
      properties:
        descriere:
          type: string
          description: Wallet desc
          example: "sunt o descriere"
        currency:
          type: integer
          example: [RON, EUR]
    error:
      type: object
      properties:
        error_code:
          type: string
          description: Wallet desc
        error_message:
          type: string

